# Generated by Django 4.2.3 on 2023-08-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Economia', '0002_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
